---
title: Synchronizer Flow
config:
  layout: elk
  htmlLabels: false
  theme: neutral
  look: handDrawn
  handDrawnSeed: 8123234
  elk:
    mergeEdges: true
    nodePlacementStrategy: LINEAR_SEGMENTS
    nodePlacementAlignment: BALANCED
    keepEntryNodeOnTop: true
  flowchart:
    defaultRenderer : elk
    wrappingWidth: 350
    inheritDir: false
---
%%{init: {"flowchart": {"defaultRenderer": "elk"}} }%%
flowchart LR
  subgraph "app"
    subgraph "Runner.java"
      startEthereumMainLoop(["`startEthereumMainLoop()`"])
    end
  end

  subgraph "ethereum"
    subgraph "eth"
      subgraph "DefaultSynchronizer.java"
        defaultSynchronizer_start[["`start()`"]]
      end
      subgraph "BlockPropagationManager.java"
        blockPropagationManager_start[["`start()`"]]
        setupListeners(["`setupListeners()`"])
        blockPropagationManager_start --> setupListeners -->listerners@{shape: brace, label: "Adds listeners like onBlockAdded, handleNewBlockFromNetwork, handleNewBlockHashesFromNetwork"}
      end
    end
  end

  startEthereumMainLoop .-> defaultSynchronizer_start
  defaultSynchronizer_start --> blockPropagationManager_start
