---
title: Runner Flow
config:
  layout: elk
  htmlLabels: false
  theme: base
  look: handDrawn
  handDrawnSeed: 58
  elk:
    mergeEdges: true
    nodePlacementStrategy: LINEAR_SEGMENTS
    nodePlacementAlignment: BALANCED
    keepEntryNodeOnTop: true
  flowchart:
    defaultRenderer : elk
    wrappingWidth: 350
    inheritDir: false
---
%%{init: {"flowchart": {"defaultRenderer": "elk"}} }%%
flowchart LR

  %% nat module %%
  subgraph "nat"
    subgraph "NatService.java"
      nat_start[["`start()`"]]
    end
  end

  %% ethereum module %%
  subgraph ethereum 
    direction LR
    %% p2p module %%
    subgraph p2p 
      subgraph "NetworkRunner.java"
        networkrunner_start[["`start()`"]]
      end
    end
    %% eth module %%
    subgraph "eth"
      subgraph "TransactionPoolEvictionService.java"
        transactionPoolEvictionService_start[["`start()`"]]
      end
    end
  end

  %% app module %%
  subgraph "app"
    direction TD
    subgraph BesuCommand.java 
      initialProcess["`initialProcess()`"]
    end
    subgraph "MiningCoordinator.java"
      mining_coordinator_start[["`start()`"]]
      mining_coordinator_subscribe@{label: "subscribe", shape: lin-rect}
    end
    subgraph "Synchronizer.java"
      synchronizer_start[["`start()`"]]
    end
    subgraph "Runner.java"
      startEthereumMainLoop(["`startEthereumMainLoop()`"])
      writeBesuPortsToFile("`writeBesuPortsToFile()`")
      writeBesuNetworksToFile("`writeBesuNetworksToFile()`")
      writePidFile("`writePidFile()`")
      startExternalServicePostMainLoop(["`startExternalServicePostMainLoop()`"])

      startEthereumMainLoop --> writeBesuPortsToFile & writeBesuNetworksToFile & writePidFile
      startEthereumMainLoop e2@--> startExternalServicePostMainLoop
    end
    initialProcess e1@--> startEthereumMainLoop
    startEthereumMainLoop --> mining_coordinator_subscribe
    startEthereumMainLoop e3@--> mining_coordinator_start
    startEthereumMainLoop e4@--> synchronizer_start

    subgraph "BesuController.java"
    end
    subgraph "BesuComponent.java"
    end
    subgraph "BesuCommandModule.java"
      command_moduel_node@{shape: brace, label: "Responsible for generating BesuCommand from BesuComponent, See dager docs to understand its creation."}
    end
  end

  startEthereumMainLoop e5@--> networkrunner_start
  startEthereumMainLoop e6@--> transactionPoolEvictionService_start
  startEthereumMainLoop e7@--> nat_start

  %% animate edges %%
  e1@{animate: true}
  e2@{animate: true}
  e3@{animate: true}
  e4@{animate: true}
  e5@{animate: true}
  e6@{animate: true}
  e7@{animate: true}
