---
title: QBFT consensus Event MESSAGE-
config:
  htmlLabels: false

  look: handDrawn
  theme: redux-dark-color

---
sequenceDiagram
  autonumber
  participant QbftController as QbftController.java
  participant QbftBlockHeightManager as QbftBlockHeightManager.java
  Participant QbftRound as QbftRound.java
  participant RoundState as RoundState.java

  alt BftMessage is instance of Commit
    QbftController ->> QbftBlockHeightManager: handleCommitPayload(Commit)
    QbftBlockHeightManager ->> QbftBlockHeightManager: actionOrBufferMessage()
    alt MessageAge == CURRENT_ROUND
      opt If currentRound is present 
        QbftBlockHeightManager ->> QbftRound: handlePrepareMessage(Commit)
        QbftRound ->> QbftRound : peerIsCommited(Commit)
        QbftRound ->> RoundState: addCommitMessage(Commit)
        RoundState ->> RoundState: updateState()
        QbftRound ->> QbftRound: importBlockToChain()
        QbftRound ->> QbftRound: notifyNewBlockListeneres(QbftBlock)
      end
    else MessageAge == FUTURE_ROUND
      QbftBlockHeightManager ->> QbftBlockHeightManager: Create new RoundState
      QbftBlockHeightManager ->> RoundState: addCommitMessage()
      RoundState --> RoundState: Update prepared and commited state in RoundState
    end
  end
