---
title: QBFT consensus Happy path round
config:
  htmlLabels: false

  theme: neutral
  look: handDrawn

---
%%{init: { }%%

sequenceDiagram
  autonumber
  participant Runner as Runner.java
  participant DefaultSynchronizer as DefaultSynchronizer.java
  participant BftMiningCoordinator as BftMiningCoordinator.java
  participant BftExecutors as BftExecutors.java
  participant BftProcessor as BftProcessor.java
  participant QbftController as QbftController.java

