---
title: QBFT Consensus startup flow
config:
  htmlLabels: false
  theme: neutral
  look: handDrawn

---
%%{init: { }%%

sequenceDiagram
  autonumber

  box "consensus/qbft-core"
    participant QbftController
  end
