---
title: QBFT consensus startup
config:
  htmlLabels: false

  theme: redux-dark-color

---
sequenceDiagram
  autonumber
  actor cli as CLI
  participant Besu as Besu.java
  participant BesuCommand as BesuCommand.java
  participant Runner as Runner.java
  participant DefaultSynchronizer as DefaultSynchronizer.java
  participant BftMiningCoordinator as BftMiningCoordinator.java
  participant BftExecutors as BftExecutors.java
  participant BftProcessor as BftProcessor.java
  participant QbftController as QbftController.java
  %% participant BftEventHandler as BftEventHandler.java %% QbftController is the implementation for this
  participant EventMultiplexer as EventMultiplexer.java

  cli ->> Besu: main()
  Besu ->> BesuCommand : parse()
  BesuCommand ->>Runner: startEthereumMainLoop()
  Runner ->> BftMiningCoordinator: subscribe()
  Note over BftMiningCoordinator: Depending on Sync State <br/> will start or stop mining Coordinator
  Runner ->> DefaultSynchronizer: start()
  Runner ->> BftMiningCoordinator: start()
  activate BftMiningCoordinator
  Note over BftMiningCoordinator: change state to Running
  BftMiningCoordinator ->>BftProcessor: start()
  BftMiningCoordinator -->>BftExecutors: start()
  Note over BftExecutors: Set state to running <br/> create thread to process bftProcessor
  BftMiningCoordinator ->>QbftController: start()
  Note over QbftController: Set state to running
  BftMiningCoordinator -->>BftExecutors: executeBftProcessor(bftProcessor)
  BftExecutors -->>BftProcessor: run()

  create participant BftEventQueue@{ type : queue } as BftEventQueue.java
  BftProcessor ->> BftEventQueue: start()
  activate BftProcessor
  Note over BftEventQueue: BlockingLinkedQueue
  loop while not bftProcessor shutdown is set true
    BftEventQueue ->> BftProcessor: poll(500ms timeout) return BftEvent
    opt if BftEvent is present 
      BftProcessor ->> EventMultiplexer: handleBftEvent(BftEvent)
    end
  end
  destroy BftEventQueue
  BftProcessor ->> BftEventQueue: stop()
  deactivate BftProcessor

  deactivate BftMiningCoordinator
