---
title: QBFT consensus Event ROUND_EXPIRY
config:
  htmlLabels: false

  look: handDrawn
  theme: redux-dark-color

---
sequenceDiagram
  autonumber
  participant BftProcessor as BftProcessor.java
  participant EventMultiplexer as EventMultiplexer.java
  participant BftEventHandlerAdaptor as BftEventHandlerAdaptor.java
  participant QbftController as QbftController.java
  participant QbftBlockHeightManager as QbftBlockHeightManager.java
  participant QbftGossiper as QbftGossiperImpl.java
  participant UniqueMessageMulticaster as UniqueMessageMulticaster.java
  participant ValidatorPeers as ValidatorPeers.java
  participant NettyPeerConnection as NettyPeerConnection.java

  create participant BftEventQueue@{ type : queue } as BftEventQueue.java
  BftProcessor ->> BftEventQueue: start()
  activate BftProcessor
  Note over BftEventQueue: BlockingLinkedQueue
  loop while not bftProcessor shutdown is set true
    BftProcessor ->>BftEventQueue: poll(500ms timeout) return BftEvent
    BftEventQueue ->> BftProcessor: BftEvent or null
    opt if BftEvent is present 
      BftProcessor ->> EventMultiplexer: handleBftEvent(BftEvent)
      alt BftEvents.Type == ROUND_EXPIRY
        EventMultiplexer ->> BftEventHandlerAdaptor: handleRoundExpiry(RoundExpiry)
        BftEventHandlerAdaptor ->> QbftController: handleRoundExpiry(RoundExpiry)
      end
    end
  end

  destroy BftEventQueue
  BftProcessor ->> BftEventQueue: stop()
  deactivate BftProcessor
