---
title: QBFT consensus happy path
config:
  htmlLabels: false

  look: handDrawn
  theme: redux-dark-color

---
sequenceDiagram
  autonumber

  participant BftExecutors as BftExecutors.java
  participant BftProcessor as BftProcessor.java
  participant EventMultiplexer as EventMultiplexer.java
  participant QbftController as QbftController.java

  BftExecutors -->>BftProcessor: run()

  create participant BftEventQueue@{ type : queue } as BftEventQueue.java
  BftProcessor ->> BftEventQueue: start()
  activate BftProcessor
  Note over BftEventQueue: BlockingLinkedQueue
  loop while not bftProcessor shutdown is set true
    BftProcessor ->>BftEventQueue: poll(500ms timeout) return BftEvent
    BftEventQueue ->> BftProcessor: BftEvent or null
    opt if BftEvent is present
      BftProcessor ->> EventMultiplexer: handleBftEvent(BftEvent)
      alt BftEvents.Type == MESSAGE
        EventMultiplexer ->> QbftController: handleMessageEvent(BftReceivedMessageEvent)
      else BftEvents.Type == ROUND_EXPIRY
        EventMultiplexer ->> QbftController: handleRoundExpiry(RoundExpiry);
      else BftEvents.Type == NEW_CHAIN_HEAD:
        EventMultiplexer ->> QbftController: handleNewBlockEvent(NewChainHead);
      else BftEvents.Type == BLOCK_TIMER_EXPIRY
        EventMultiplexer ->> QbftController: handleBlockTimerExpiry(BlockTimerExpiry);
      end
    end
  end
  destroy BftEventQueue
  BftProcessor ->> BftEventQueue: stop()
  deactivate BftProcessor

